### ISSUE TITLE
Elastalert already installed

### ISSUE THREAD

**Issue by ghasec** [bitsensor/elastalert#196]
Hello, if elastalert is already installed how to just add the configuration of server, and wich file it need to be modified for setting on IP:3030

Kind regards,
Rali

**Comment by nsano-rururu** [comment]
It's been a long time since the development was completed, and no one can answer the question.

**Comment by nsano-rururu** [comment]
If you can handle the error yourself

It may be possible to move it based on the following reference information with elasticsearch running and only installing elastalert, or it may not work because the version of npm and node is too new.
https://github.com/johnsusek/praeco#setting-up-the-api-server

**Comment by nsano-rururu** [comment]
Please close
